grammar = { 
	"INICIO": [['sentences']],
	"sentences": [['sentence', 'temp_sentences']],
	"temp_sentences": [['sentences'], ['&']],
	"sentence": [['if_conditional_sentence'], ['while_sentence'], ['for_sentence'], ['assign_sentence'], ['write_sentence'], ['sub_declare'], ['go_label'], ['builtin_declare']],
	"builtin_declare": [['Program', 'builtin_block'], ['Stack', 'builtin_block'], ['Array', 'builtin_block']],
	"builtin_block": [['tkn_period', 'id', 'tkn_left_paren', 'arguments', 'tkn_right_paren']],
	"arguments": [['param_option', 'builtin_param'], ['&']],
	"builtin_param": [['tkn_comma', 'param_option', 'builtin_param'], ['&']],
	"param_option": [['myvar'], ['&']],
	"assign_sentence": [['id', 'assign_sentence1']],
	"array_continue": [['tkn_left_brac', 'myvar', 'tkn_right_brac', 'tkn_equals', 'myvar'], ['tkn_equals', 'expr'], ['&']],
	"temp_sentence": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'tkn_right_paren'], ['expr'], ['builtin_declare']],
	"write_sentence": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'write_sentence1']],
	"if_conditional_sentence": [['If', 'tkn_left_paren', 'expr_conditional', 'tkn_right_paren', 'Then', 'sentences', 'elseif_conditional', 'else_conditional', 'EndIf']],
	"elseif_conditional": [['ElseIf', 'tkn_left_paren', 'expr_conditional', 'tkn_right_paren', 'Then', 'sentences', 'elseif_conditional'], ['&']],
	"else_conditional": [['Else', 'sentences'], ['&']],
	"label": [['id', 'tkn_colon']],
	"go_label": [['Goto', 'id']],
	"while_sentence": [['While', 'tkn_left_paren', 'expr_conditional', 'tkn_right_paren', 'sentences', 'EndWhile']],
	"for_sentence": [['For', 'myvar', 'tkn_equals', 'expr', 'To', 'expr_conditional', 'for_sentence1']],
	"sub_declare": [['Sub', 'id', 'sub_block', 'EndSub']],
	"sub_block": [['sub_sentences'], ['&']],
	"sub_sentences": [['sub_sentence', 'temp_sentences']],
	"sub_sentence": [['if_conditional_sentence'], ['while_sentence'], ['for_sentence'], ['assign_sentence'], ['write_sentence'], ['go_label'], ['builtin_declare']],
	"expr": [['tkn_left_paren', 'expr', 'tkn_right_paren', 'expr1'], ['write_sentence'], ['tkn_minus', 'expr'], ['myvar', 'expr1']],
	"expr1": [['op', 'expr'], ['conector', 'expr'], ['&']],
	"expr_conditional": [['builtin_declare', 'expr_conditional'], ['op_conditional', 'myvar'], ['tkn_minus', 'expr_conditional'], ['write_sentence'], ['myvar', 'expr_conditional1'], ['tkn_left_paren', 'myvar', 'expr_conditional11']],
	"expr_conditional1": [['op_conditional', 'expr_conditional'], ['conector', 'expr_conditional'], ['&']],
	"text": [['myvar', 'temp_text']],
	"temp_text": [['tkn_plus', 'myvar', 'temp_text'], ['&']],
	"myvar": [['id', 'temp_var'], ['builtin_declare'], ['tkn_number'], ['True'], ['False'], ['tkn_text']],
	"temp_var": [['tkn_left_brac', 'myvar', 'tkn_right_brac'], ['&']],
	"conector": [['And'], ['Or']],
	"op": [['tkn_plus'], ['tkn_minus'], ['tkn_times'], ['tkn_div'], ['tkn_diff'], ['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater']],
	"op_conditional": [['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater'], ['tkn_equals'], ['tkn_plus'], ['tkn_times'], ['tkn_minus'], ['tkn_div'], ['tkn_diff']],
	"assign_sentence1": [['tkn_equals', 'temp_sentence'], ['tkn_colon'], ['tkn_left_brac', 'myvar', 'tkn_right_brac', 'array_continue'], ['tkn_left_paren', 'tkn_right_paren']],
	"write_sentence1": [['text', 'tkn_right_paren'], ['id', 'tkn_right_paren'], ['expr', 'tkn_right_paren'], ['tkn_right_paren']],
	"for_sentence1": [['sentences', 'EndFor'], ['Step', 'expr', 'sentences', 'EndFor']],
	"expr_conditional11": [['op_conditional', 'expr_conditional', 'expr_conditional1', 'tkn_right_paren', 'expr_conditional1'], ['conector', 'expr_conditional', 'tkn_right_paren']],
}