grammar = { 
	"INICIO": [['sentencias']],
	"sentencias": [['sentencia', 'sentencias'], ['&']],
	"sentencia": [['sentencia_condicional_if'], ['sentencia_while'], ['sentencia_for'], ['sentencia_de_asignacion'], ['sentencia_escritura'], ['declarar_subrutina'], ['ir_a_etiqueta'], ['funcion_built_in']],
	"funcion_built_in": [['Stack', 'tkn_period', 'id', 'tkn_left_paren', 'variable', 'parametros_built_in', 'tkn_right_paren'], ['Array', 'tkn_period', 'id', 'tkn_left_paren', 'variable', 'parametros_built_in', 'tkn_right_paren'], ['Program', 'tkn_period', 'id', 'tkn_left_paren', 'funcion_built_in°']],
	"parametros_built_in": [['tkn_comma', 'variable', 'parametros_built_in'], ['&']],
	"sentencia_de_asignacion": [['id', 'sentencia_de_asignacion°']],
	"continuar_array": [['tkn_left_brac', 'variable', 'tkn_right_brac', 'tkn_equals', 'variable'], ['tkn_equals', 'variable'], ['&']],
	"otra_sentencia": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'tkn_right_paren']],
	"sentencia_escritura": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'sentencia_escritura°']],
	"sentencia_condicional_if": [['If', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'Then', 'contenido_subrutina', 'condicional_ElseIf', 'condicional_Else', 'EndIf']],
	"condicional_ElseIf": [['ElseIf', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'Then', 'contenido_subrutina', 'condicional_ElseIf'], ['&']],
	"condicional_Else": [['Else', 'condicional_Else'], ['&']],
	"etiqueta": [['id', 'tkn_colon']],
	"ir_a_etiqueta": [['Goto', 'id']],
	"sentencia_while": [['While', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'contenido_subrutina', 'EndWhile']],
	"sentencia_for": [['For', 'id', 'tkn_equals', 'tkn_number', 'To', 'tkn_number', 'sentencia_for°']],
	"declarar_subrutina": [['Sub', 'id', 'contenido_subrutina', 'EndSub']],
	"contenido_subrutina": [['sentencia_sub', 'contenido_subrutina'], ['&']],
	"sentencia_sub": [['sentencia_condicional_if'], ['sentencia_while'], ['sentencia_for'], ['sentencia_de_asignacion'], ['sentencia_escritura'], ['ir_a_etiqueta'], ['funcion_built_in']],
	"expresion": [['tkn_minus', 'expresion'], ['variable', 'expresion°'], ['tkn_left_paren', 'variable', 'expresion°°']],
	"expresion_condicion": [['variable', 'expresion_condicion°'], ['tkn_left_paren', 'variable', 'expresion_condicion°°']],
	"texto": [['variable', 'texto_aux']],
	"texto_aux": [['tkn_plus', 'variable', 'texto_aux'], ['&']],
	"variable": [['id', 'variable_aux'], ['tkn_number'], ['True'], ['False'], ['tkn_text']],
	"variable_aux": [['tkn_left_brac', 'variable', 'tkn_right_brac'], ['&']],
	"conector": [['And'], ['Or']],
	"operador": [['tkn_plus'], ['tkn_minus'], ['tkn_times'], ['tkn_div'], ['tkn_diff'], ['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater']],
	"operador_condicion": [['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater']],
	"funcion_built_in°": [['id', 'tkn_right_paren'], ['tkn_number', 'tkn_right_paren']],
	"sentencia_de_asignacion°": [['tkn_equals', 'expresion', 'funcion_built_in'], ['tkn_colon'], ['tkn_left_brac', 'variable', 'tkn_right_brac', 'continuar_array'], ['tkn_left_paren', 'tkn_right_paren']],
	"sentencia_escritura°": [['texto', 'tkn_right_paren'], ['id', 'tkn_right_paren'], ['tkn_right_paren']],
	"sentencia_for°": [['contenido_subrutina', 'EndFor'], ['Step', 'tkn_number', 'contenido_subrutina', 'EndFor']],
	"expresion°": [['operador', 'expresion'], ['conector', 'expresion'], ['&']],
	"expresion°°": [['operador', 'expresion', 'tkn_right_paren'], ['conector', 'expresion', 'tkn_right_paren']],
	"expresion_condicion°": [['operador_condicion', 'expresion_condicion'], ['conector', 'expresion_condicion'], ['&']],
	"expresion_condicion°°": [['operador_condicion', 'expresion_condicion', 'tkn_right_paren'], ['conector', 'expresion_condicion', 'tkn_right_paren']],
}