grammar = { 
	"INICIO": [['sentencias']],
	"sentencias": [['sentencia', 'sigue']],
	"sigue": [['sentencias'], ['&']],
	"sentencia": [['sentencia_condicional_if'], ['sentencia_while'], ['sentencia_for'], ['sentencia_de_asignacion'], ['sentencia_escritura'], ['declarar_subrutina'], ['ir_a_etiqueta'], ['funcion_built_in']],
	"funcion_built_in": [['Stack', 'tkn_period', 'id', 'tkn_left_paren', 'variable', 'parametros_built_in', 'tkn_right_paren'], ['Array', 'tkn_period', 'id', 'tkn_left_paren', 'variable', 'parametros_built_in', 'tkn_right_paren'], ['Program', 'tkn_period', 'id', 'tkn_left_paren', 'funcion_built_in1']],
	"parametros_built_in": [['tkn_comma', 'opcion_parametro', 'parametros_built_in'], ['&']],
	"opcion_parametro": [['variable'], ['&']],
	"sentencia_de_asignacion": [['id', 'sentencia_de_asignacion1']],
	"continuar_array": [['tkn_left_brac', 'variable', 'tkn_right_brac', 'tkn_equals', 'variable'], ['tkn_equals', 'variable'], ['&']],
	"otra_sentencia": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'tkn_right_paren'], ['expresion'], ['funcion_built_in']],
	"sentencia_escritura": [['TextWindow', 'tkn_period', 'id', 'tkn_left_paren', 'sentencia_escritura1']],
	"sentencia_condicional_if": [['If', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'Then', 'sentencias', 'condicional_ElseIf', 'condicional_Else', 'EndIf']],
	"condicional_ElseIf": [['ElseIf', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'Then', 'sentencias', 'condicional_ElseIf'], ['&']],
	"condicional_Else": [['Else', 'sentencias'], ['&']],
	"etiqueta": [['id', 'tkn_colon']],
	"ir_a_etiqueta": [['Goto', 'id']],
	"sentencia_while": [['While', 'tkn_left_paren', 'expresion_condicion', 'tkn_right_paren', 'sentencias', 'EndWhile']],
	"sentencia_for": [['For', 'id', 'tkn_equals', 'tkn_number', 'To', 'tkn_number', 'sentencia_for1']],
	"declarar_subrutina": [['Sub', 'id', 'contenido_subrutina', 'EndSub']],
	"contenido_subrutina": [['sentencias_subrutina'], ['&']],
	"sentencias_subrutina": [['sentencia_sub', 'sigue']],
	"sentencia_sub": [['sentencia_condicional_if'], ['sentencia_while'], ['sentencia_for'], ['sentencia_de_asignacion'], ['sentencia_escritura'], ['ir_a_etiqueta'], ['funcion_built_in']],
	"expresion": [['tkn_minus', 'expresion'], ['variable', 'expresion1'], ['tkn_left_paren', 'variable', 'expresion11']],
	"expresion_condicion": [['variable', 'expresion_condicion1'], ['tkn_left_paren', 'variable', 'expresion_condicion11']],
	"texto": [['variable', 'texto_aux']],
	"texto_aux": [['tkn_plus', 'variable', 'texto_aux'], ['&']],
	"variable": [['id', 'variable_aux'], ['tkn_number'], ['True'], ['False'], ['tkn_text']],
	"variable_aux": [['tkn_left_brac', 'variable', 'tkn_right_brac'], ['&']],
	"conector": [['And'], ['Or']],
	"operador": [['tkn_plus'], ['tkn_minus'], ['tkn_times'], ['tkn_div'], ['tkn_diff'], ['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater']],
	"operador_condicion": [['tkn_leq'], ['tkn_geq'], ['tkn_less'], ['tkn_greater']],
	"funcion_built_in1": [['id', 'tkn_right_paren'], ['tkn_number', 'tkn_right_paren']],
	"sentencia_de_asignacion1": [['tkn_equals', 'otra_sentencia'], ['tkn_colon'], ['tkn_left_brac', 'variable', 'tkn_right_brac', 'continuar_array'], ['tkn_left_paren', 'tkn_right_paren']],
	"sentencia_escritura1": [['texto', 'tkn_right_paren'], ['id', 'tkn_right_paren'], ['tkn_right_paren']],
	"sentencia_for1": [['sentencias', 'EndFor'], ['Step', 'tkn_number', 'sentencias', 'EndFor']],
	"expresion1": [['operador', 'expresion'], ['conector', 'expresion'], ['&']],
	"expresion11": [['operador', 'expresion', 'tkn_right_paren'], ['conector', 'expresion', 'tkn_right_paren']],
	"expresion_condicion1": [['operador_condicion', 'expresion_condicion'], ['conector', 'expresion_condicion'], ['&']],
	"expresion_condicion11": [['operador_condicion', 'expresion_condicion', 'tkn_right_paren'], ['conector', 'expresion_condicion', 'tkn_right_paren']],
}